---
- name: Build StorageGrid from OVA
  hosts: localhost
  gather_facts: false

  vars_files:
  - vars/vars_vcenter_exampleLab.yml
  - vars/vars_storagegrid_exampleLab.yml
  vars:
    #ovf_version:           "11.5.0"
    # grid_name:            "sgws"
    # grid_network_name:    "VM Network"
    # grid_network_config:  "STATIC"
    # grid_network_mask:    255.255.255.0
    # grid_network_gateway: 192.168.7.1
    # admin_ip:             192.168.7.215

  tasks:

  # Deploy Admin Node
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_Admin_Node"
      vm_name:          "{{ sg.grid_name }}-admin"
      ovf_hostname:     "{{ sg.grid_name }}-admin"
      grid_network_ip:  "{{ sg.admin_ip }}"
      vm_memory_mb:     "{{ sg.admin.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.admin.vm_num_cpus }}"
    when: sg.admin.deploy is true

  # Deploy Storage Node 1
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_Storage_Node"
      vm_name:          "{{ sg.grid_name }}-storage1"
      ovf_hostname:     "{{ sg.grid_name }}-storage1"
      grid_network_ip:  "{{ sg.storage1.grid_network_ip }}"
      vm_memory_mb:     "{{ sg.storage1.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.storage1.vm_num_cpus }}"
    when: sg.storage1.deploy is true

  # Deploy Storage Node 2
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_Storage_Node"
      vm_name:          "{{ sg.grid_name }}-storage2"
      ovf_hostname:     "{{ sg.grid_name }}-storage2"
      grid_network_ip:  "{{ sg.storage2.grid_network_ip }}"
      vm_memory_mb:     "{{ sg.storage2.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.storage2.vm_num_cpus }}"
    when: sg.storage2.deploy is true

  # Deploy Storage Node 3
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_Storage_Node"
      vm_name:          "{{ sg.grid_name }}-storage3"
      ovf_hostname:     "{{ sg.grid_name }}-storage3"
      grid_network_ip:  "{{ sg.storage3.grid_network_ip }}"
      vm_memory_mb:     "{{ sg.storage3.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.storage3.vm_num_cpus }}"
    when: sg.storage3.deploy is true

  # Deploy Storage Node 4
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_Storage_Node"
      vm_name:          "{{ sg.grid_name }}-storage4"
      ovf_hostname:     "{{ sg.grid_name }}-storage4"
      grid_network_ip:  "{{ sg.storage4.grid_network_ip }}"
      vm_memory_mb:     "{{ sg.storage4.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.storage4.vm_num_cpus }}"
    when: sg.storage4.deploy is true

  # Deploy Gateway Node
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_API_Gateway"
      vm_name:          "{{ sg.grid_name }}-gateway"
      ovf_hostname:     "{{ sg.grid_name }}-gateway"
      grid_network_ip:  "{{ sg.gateway.grid_network_ip }}"
      vm_memory_mb:     "{{ sg.gateway.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.gateway.vm_num_cpus }}"
    when: sg.gateway.deploy is true

  # Deploy Non-Primary Admin Node
  - include_role:
      name: build_storagegrid_node_from_ova
    vars:
      node_type:        "VM_Admin_Node"
      admin_role:       "Non-Primary"
      vm_name:          "{{ sg.grid_name }}-admin2"
      ovf_hostname:     "{{ sg.grid_name }}-admin2"
      grid_network_ip:  "{{ sg.admin2.grid_network_ip }}"
      vm_memory_mb:     "{{ sg.admin2.vm_memory_mb }}"
      vm_num_cpus:      "{{ sg.admin2.vm_num_cpus }}"
    when: sg.admin2.deploy is true
