---
- hosts: localhost
  name: Build ONTAP Simulator from OVA
  gather_facts: false
  collections:
    - community.vmware
  vars:
    # ovf_file:           files/ONTAP/vsim-netapp-DOT9.9.1-cm_nodar.ova
    ovf_file:           "files/ONTAP/vsim-netapp-DOT{{ ovf_version }}-cm_nodar.ova"
    ovf_version:        "9.9.1"
    

    vcenter_address:    vcenter.demo.lab
    vcenter_username:   administrator@vsphere.local
    vcenter_password:   ChangeMe2!
    vcenter_datacenter: "Datacenter 1"
    vm_datastore:       "datastore1"
  vars_files:
    - vars/vars_vcenter_exampleLab.yml
    - vars/vars_ontap_redshirt.yml

  tasks:
    
    - name: Deploy VSIM Second node
      include_role:
        name: deploy_ovf_vsim
      vars:
        vm_name:              "{{ clus.name }}-02"
        sys_serial_number:    "4034389-06-2"
        nvram_sysid:          "4034389062"
        cluster_setup:        false
        # ontap_cluster_name:   "{{ cluster }}"
        vm_num_nics:          6
        ontap_node_mgmt_ip:   "{{ clus.node2.node_mgmt_ip }}"
        ontap_netmask:        "{{ clus.netmask }}"
        ontap_gateway:        "{{ clus.gateway }}"
        # ontap_cluster_mgmt_ip: "{{ clus.mgmt }}"
        # set_admin_password:   true  # Impliied with cluster create
        # ontap_password:       netapp1234
        force:                true  # Overwrite if exists - Repave
        data_network:         "VM Network"
        cluster_network:      "GRID Network"

    - name: Initial cluster & node
      include_role:
        name: deploy_ovf_vsim
      vars:
        vm_name:              "{{ clus.name }}-01"
        sys_serial_number:    "4082368-50-7"
        ontap_cluster_name:   "{{ cluster }}"
        vm_num_nics:          6
        ontap_node_mgmt_ip:   "{{ clus.node1.node_mgmt_ip }}"
        ontap_netmask:        "{{ clus.netmask }}"
        ontap_gateway:        "{{ clus.gateway }}"
        ontap_cluster_mgmt_ip: "{{ clus.mgmt }}"
        # set_admin_password:   true  # Impliied with cluster create
        ontap_password:       netapp1234
        add_nodes_by_serial:  "4034389-06-2"
        force:                true  # Overwrite if exists - Repave
        data_network:         "VM Network"
        cluster_network:      "GRID Network"
  
    

   

    
