---
- name: "Remove virtual machine {{ vm_name }}"
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
  - community.vmware

  vars_files:
  - vars/vars_vcenter_exampleLab.yml
  vars:
    sgvms:
    # - TEST-SGWS-Gateway
    # - TEST-SGWS-Admin2
    # - TEST-SGWS-Admin
    # - TEST-SGWS-Storage1
    # - TEST-SGWS-Storage2
    # - TEST-SGWS-Storage3
    # - TEST-SGWS-Storage4
    - sgws-admin
    - sgws-admin2
    - sgws-gateway
    - sgws-storage1
    - sgws-storage2
    - sgws-storage3
    - sgws-storage4

  tasks:

  # Shutdown and Remove StorageGRID Nodes
  # - name: Shutdown and Remove SG VMs
  #   include_tasks: ../tasks/remove_vm_guests.yml
  #   vars:
  #     vm_name:    "{{ item }}"
  #     state:      absent
  #   loop:         "{{ sgvms }}"
  #   register:     facts

# Deploy Admin Node
  - include_role:
      name: remove_storagegrid_vms
    vars:
      vars:
      vm_name:    "{{ item }}"
      state:      absent
    loop:         "{{ sgvms }}"
    register:     facts
