---
- name: 'StorageGRID: Configure Fabric Pool'
  hosts: localhost
  gather_facts: no
  collections:
  - netapp.storagegrid
  vars_files:
  - vars_sg.yml
  vars:
    grid_auth: &grid_auth
      api_url:                 "{{ grid_admin_base_url }}"
      auth_token:              "{{ auth_response.json.data }}"
      validate_certs:          false
    tenant_auth: &tenant_auth
      api_url:                  "{{ grid_admin_base_url }}"
      auth_token:               "{{ tenant_auth_response.json.data }}"
      validate_certs:           false

  tasks:

  ###
  # GRID Authorization
  - name: Get GRID authorization token
    uri:
      url:                     "{{ grid_admin_base_url }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ grid_admin_username }}",
        "password":            "{{ grid_admin_password }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: auth_response

  ###
  # Create Tenant
  - name: Create a GRID tenant
    na_sg_grid_account:
      <<: *grid_auth

      state:                   present
      name:                    "{{ tenant.root_username }}"
      protocol:                s3
      management:              true
      use_own_identity_source: false
      allow_platform_services: false
      # password:                "{{ tenant.root_passwd }}"
      password:                fabricpool_passwd
      update_password:         on_create
      # quota_size:              "{{ (DEFAULT_QUOTA | int ) * ( 1000 | pow(3) ) | int }}"
      # quota_size_unit:         bytes

    no_log: false
    register: fp_account_results

  - name: Print GRID Tenant account response
    debug:
      msg:
      - "{{ fp_account_results }}"

  - name: Print accountId
    debug:
      msg:
      - "{{ fp_account_results.resp.id }}"

  ###
  # GET tenant infor by API

  - name: GET Tenant AUTH token
    uri:
      url:                     "{{ grid_admin_base_url }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "accountId":           "{{ fp_account_results.resp.id }}",
        "username":            "{{ tenant.root_username }}",
        "password":            "{{ tenant.root_passwd }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: tenant_auth_response


  # - name: Print GRID response
  #   debug:
  #     msg:
  #     - "{{ fp_account_results }}"