---
- name: 'StorageGRID: Create admin user: {{ grid_admin_non_root }}'
  hosts: localhost
  gather_facts: no
  collections:
  - netapp.storagegrid
  vars_files:
  - vars_sg.yml
  vars:
    grid_auth: &grid_auth
      api_url:                 "{{ grid_admin_base_url }}"
      auth_token:              "{{ auth_response.json.data }}"
      validate_certs:          false

  tasks:

  - name: Get GRID authorization token
    uri:
      url:                     "{{ grid_admin_base_url }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ grid_admin_username }}",
        "password":            "{{ grid_admin_password }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: auth_response

  - name: Create non-root admin account on StorageGRID
    netapp.storagegrid.na_sg_grid_user:
      <<: *grid_auth

      state:        present
      full_name:    "{{ item }}"
      unique_name:  "user/{{ item }}"
      member_of:    "group/{{ grid_admin_group }}"
      password:     "{{ grid_admin_non_root_password }}"
      disable:      false

    register: grid_admin_results
    loop: "{{ grid_admin_non_root }}"

  - name: Print GRID response
    debug:
      msg:
      - "{{ grid_admin_results }}"