###
#  Ansible vars file sample for role configuration varibles: basic ONTAP cluster & vserver config
#  Note:  Supports 2 X ONTAP VSIMs within a single cluster. 
#  Each has:
#     6 X network ports
#     40+ disks
###

###
# Role-Based Configuration: Cluster
###

# VSIM license's code
# license_codes: QDDSVRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,ANGJKUNFXMSMUCEZFAAAAAAAAAAA,UFTUNUNFXMSMUCEZFAAAAAAAAAAA
license_codes: "{{ licenses }}"

disks:  # disks module assigns all visible disks to a node. This may be done during Day 0 Installation process
- "{{ clus.name }}-01"
- "{{ clus.name }}-02"

dns:    # Set DNS for Cluster
- { dns_domains: "{{ dns_domain }}", dns_nameservers: "{{ dns_srvrs }}" }

ntp:    # Set NTP Server (requires the cluster to have DNS set)
- { server_name: "{{ time }}", version: auto }

aggrs:  # Create one or more Aggregates.
- { name: "{{ clus.aggr }}_01_aggr1", node: "{{ clus.name }}-01", disk_count: 40, max_raid: 20 }
- { name: "{{ clus.aggr }}_02_aggr1", node: "{{ clus.name }}-02", disk_count: 40, max_raid: 20 }

ports:  # Set MTU for ports
- { node: "{{ clus.name }}-01", port: e0d, mtu: 1500, flowcontrol: none }
- { node: "{{ clus.name }}-01", port: e0e, mtu: 1500, flowcontrol: none }
- { node: "{{ clus.name }}-01", port: e0f, mtu: 1500, flowcontrol: none }
- { node: "{{ clus.name }}-02", port: e0d, mtu: 1500, flowcontrol: none }
- { node: "{{ clus.name }}-02", port: e0e, mtu: 1500, flowcontrol: none }
- { node: "{{ clus.name }}-02", port: e0f, mtu: 1500, flowcontrol: none }

ifgrps:  # Create and add ports to Interface Groups.
- { name: a0a, node: "{{ clus.name }}-01", ports: "{{ ifgrp_ports }}", mode: multimode_lacp, mtu: 1500 }
- { name: a0a, node: "{{ clus.name }}-02", ports: "{{ ifgrp_ports }}", mode: multimode_lacp, mtu: 1500 }

vlans:  # Create vlans on LIFS
# - { id: "{{ vlan_id }}", node: "{{ cluster }}-01", parent: a0a }
# - { id: "{{ vlan_id }}", node: "{{ cluster }}-02", parent: a0a }

bcasts:  # Create Broadcast domains
- { name: "{{ bd.nas }}", mtu: 1500, ipspace: default,
    ports: "{{ clus.name }}-01:a0a,{{ clus.name }}-01:e0e,{{ clus.name }}-02:a0a,{{ clus.name }}-02:e0e" }
# - { name: "{{ bd.mgmt }}", mtu: 1500, ipspace: default,
#     ports: '{{ clus.name }}-01:e0M,{{ clus.name }}-02:e0M,{{ clus.name }}-01:e0e,{{ clus.name }}-02:e0e' }
- { name: "{{ bd.mgmt }}", mtu: 1500, ipspace: default,
    ports: '{{ clus.name }}-01:e0c,{{ clus.name }}-02:e0c,{{ clus.name }}-01:e0d,{{ clus.name }}-02:e0d' }


inters: # Create intercluster lifs for SnapMirror.
- { name: "{{ clus.name }}-01_icl1", address: "{{ node1.icl }}", netmask: "{{ svm_netmask }}",
    node: "{{ clus.name }}-01", port: e0d }
- { name: "{{ clus.name }}-02_icl2", address: "{{ node2.icl }}", netmask: "{{ svm_netmask }}",
    node: "{{ clus.name }}-02", port: e0d }


###
# Role-Based Configuration: Vserver (SVM)
###

vservers:  # Vservers to create # aggr_list is optional.  If not specified, defaults to all aggregates.
- { name: "{{ svm }}", aggr: "{{ clus.aggr }}_01_aggr1", protocol: nfs,
    aggr_list: "{{ svm_aggrs }}" }

vserver_dns:  # DNS at the Vserver level
- { vserver: "{{ svm }}", dns_domains: "{{ svm_dns_domain }}", dns_nameservers: "{{ svm_dns_srvrs }}" }
# - { vserver: "{{ svm }}", dns_domains: example.com, dns_nameservers: 8.8.8.8 }  # incase no DNS is available locally

lifs:  # interfaces for the Vservers being created
- { name: "{{ svm }}_data1", vserver: "{{ svm }}", node: "{{ clus.name }}-01", port: a0a, protocol: nfs,
    address: "{{ node1.svm_lif1 }}", netmask: "{{ svm_netmask }}" }
- { name: "{{ svm }}_data2", vserver: "{{ svm }}", node: "{{ clus.name }}-02", port: a0a, protocol: nfs,
    address: "{{ node2.svm_lif2 }}", netmask: "{{ svm_netmask }}" }

gateway:  # To configure the default route/gateway for the vservers
- { vserver: "{{ svm }}", destination: 0.0.0.0/0, gateway: "{{ svm_gateway }}" }
