---
- name: "Remove virtual machine"
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - community.vmware

  vars_files:
    - ../vars/vars_vcenter_exampleLab.yml
  vars:
    vms:
      # - aiqum
      - AIQUM
      # - sgws-admin
      # - sgws-admin2
      # - sgws-gateway
      # - sgws-storage1
      # - sgws-storage2
      # - sgws-storage3
      # - sgws-storage4

  tasks:
    # Shutdown and Remove StorageGRID Nodes
    - name: "Shutdown and Remove VMs {{ item }}"
      include_tasks: ../tasks/remove_vm_guests.yml
      vars:
        vm_name: "{{ item }}"
        state: absent
      loop: "{{ vms }}"
      register: facts
